<?php
    define('BASE_URL',"http://teenshop.local/");
    define('BASE_ADMIN',BASE_URL."@admincp");
    define('TEMPLATE_AMIN',BASE_URL."templates/backend/green/");
    define('TEMPLATE_FRONTEND',BASE_URL."templates/frontend/version3/");
    define('URL_UPLOAD',BASE_URL."uploads/");
    define('URL_UPLOAD_PRODUCT',BASE_URL."uploads/product/");
    define('URL_UPLOAD_CATEGORY',BASE_URL."uploads/category/");
    define('URL_UPLOAD_NEWS',BASE_URL."uploads/blog/");